apiversion: apps/v1
kind: Deployment
metadata: 
  name: my-application
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:latest
          ports:
            - containerPort: 8000
          env: 
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database-url
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/ready"
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3
      imagePullSecrets:
        - name: my-registry-key